# Site Info
title: 달콤하지만은 않은 일상들
tagline: '재미있게 살자!!!'
description: '재미있게 살자!!!'
baseurl: ""
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: 노르웨이숲
  description: 달콤하지만은 않은 일상들
  img: /public/img/main.jpg

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Post:
    - '/blog/'
  Categories:
    - '/blog/categories/'
  Tags:
    - '/blog/tags/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

main:
  image: /public/img/main.jpg
  caption: 재미있게 살자!!!

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-89877408-1' # leave blank if you don't want google analytics
naver_analytics_token: '1293c760f8c51'
disqus_short_name: 'pptwenty-github-io' # leave blank if you don't want disqus
